"""Stamp the build version: YYYYMMDD.XX (XX = build number for that day, starting at 01).

Writes app/version.py and prints the exe base name, e.g. wauncher_20261001_01.
"""
import datetime as _dt
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERSION_FILE = os.path.join(ROOT, "app", "version.py")
DIST = os.path.join(ROOT, "dist")
APP_ID = "wauncher"


def current_version() -> str | None:
    try:
        text = open(VERSION_FILE, encoding="utf-8").read()
    except OSError:
        return None
    m = re.search(r'VERSION\s*=\s*"(\d{8}\.\d{2,})"', text)
    return m.group(1) if m else None


def next_version(today: str) -> str:
    seq = 0
    cur = current_version()
    if cur and cur.startswith(today + "."):
        seq = max(seq, int(cur.split(".")[1]))
    if os.path.isdir(DIST):
        for name in os.listdir(DIST):
            m = re.match(rf"{APP_ID}_{today}_(\d+)\.exe$", name)
            if m:
                seq = max(seq, int(m.group(1)))
    return f"{today}.{seq + 1:02d}"


def main() -> None:
    today = _dt.date.today().strftime("%Y%m%d")
    version = sys.argv[1] if len(sys.argv) > 1 else next_version(today)
    if not re.fullmatch(r"\d{8}\.\d{2,}", version):
        sys.exit(f"bad version {version!r}; expected YYYYMMDD.XX")
    with open(VERSION_FILE, "w", encoding="utf-8") as fh:
        fh.write('"""Generated by tools/bump_version.py at build time. Do not edit by hand."""\n')
        fh.write(f'VERSION = "{version}"\n')
    print(f"{APP_ID}_{version.replace('.', '_')}")


if __name__ == "__main__":
    main()
